variables:
  NEXT_PUBLIC_BASE_URL: $NEXT_PUBLIC_BASE_URL
  NEXT_PUBLIC_SSHOC_API_BASE_URL: $NEXT_PUBLIC_SSHOC_API_BASE_URL
  NEXT_PUBLIC_GITLAB_BASE_URL: $NEXT_PUBLIC_GITLAB_BASE_URL
  NEXT_PUBLIC_GITLAB_REPOSITORY: $NEXT_PUBLIC_GITLAB_REPOSITORY
  NEXT_PUBLIC_GITLAB_REPOSITORY_BRANCH: $NEXT_PUBLIC_GITLAB_REPOSITORY_BRANCH
  NEXT_PUBLIC_GITLAB_APP_ID: $NEXT_PUBLIC_GITLAB_APP_ID
  NEXT_PUBLIC_MATOMO_BASE_URL: $NEXT_PUBLIC_MATOMO_BASE_URL
  NEXT_PUBLIC_MATOMO_APP_ID: $NEXT_PUBLIC_MATOMO_APP_ID

include:
  - template: Auto-DevOps.gitlab-ci.yml
