stages:
  - build
  - validate
  - test
  - package

variables:
  CYPRESS_CACHE_FOLDER: "${CI_PROJECT_DIR}/.cache/Cypress"
  YARN_CACHE_FOLDER: "${CI_PROJECT_DIR}/.cache/yarn"

.cache:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/yarn
      - .cache/Cypress

install:
  stage: build
  extends: .cache
  image: node:12-alpine
  script:
    - yarn --frozen-lockfile --silent
  only:
    changes:
      - yarn.lock

validate:
  image: node:12-alpine
  stage: validate
  extends: .cache
  cache:
    policy: pull
  script:
    - yarn --frozen-lockfile --silent
    - yarn commitlint --from=main --to=$CI_COMMIT_SHA
    - yarn format
    - yarn lint

test:
  stage: test
  image: node:12-alpine
  extends: .cache
  cache:
    policy: pull
  script:
    - yarn --frozen-lockfile --silent
    - yarn test

test:e2e:
  stage: test
  image: cypress/base:12
  extends: .cache
  cache:
    policy: pull
  script:
    - yarn --frozen-lockfile --silent
    - yarn test:e2e
  artifacts:
    when: on_failure
    paths:
      - cypress/screenshots
      - cypress/videos
    expire_in: 1 day

.docker:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - sshoc-frontend
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.frontend:
  script:
    - docker pull $DOCKER_RELEASE_IMAGE || true
    - docker build --cache-from $DOCKER_RELEASE_IMAGE --build-arg
      REACT_APP_API_BASE_URL --tag $DOCKER_CURRENT_IMAGE --tag
      $DOCKER_RELEASE_IMAGE .
    - docker push $DOCKER_CURRENT_IMAGE
    - docker push $DOCKER_RELEASE_IMAGE

.storybook:
  script:
    - docker pull $DOCKER_RELEASE_IMAGE || true
    - docker build -f Dockerfile-storybook --cache-from $DOCKER_RELEASE_IMAGE
      --tag $DOCKER_CURRENT_IMAGE --tag $DOCKER_RELEASE_IMAGE .
    - docker push $DOCKER_CURRENT_IMAGE
    - docker push $DOCKER_RELEASE_IMAGE

package:frontend:main:acdh:
  stage: package
  extends:
    - .docker
    - .frontend
  variables:
    DOCKER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/frontend:latest
    DOCKER_CURRENT_IMAGE: ${CI_REGISTRY_IMAGE}/frontend:$CI_COMMIT_SHORT_SHA
    REACT_APP_API_BASE_URL: https://sshoc-marketplace-api.acdh-dev.oeaw.ac.at
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

package:frontend:tags:acdh:
  stage: package
  extends:
    - .docker
    - .frontend
  variables:
    DOCKER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/frontend:release
    DOCKER_CURRENT_IMAGE: ${CI_REGISTRY_IMAGE}/frontend:$CI_COMMIT_TAG
    REACT_APP_API_BASE_URL: https://marketplace-api.sshopencloud.eu
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG'

package:storybook:main:acdh:
  stage: package
  extends:
    - .docker
    - .storybook
  variables:
    DOCKER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/storybook:latest
    DOCKER_CURRENT_IMAGE: ${CI_REGISTRY_IMAGE}/storybook:$CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

package:storybook:tags:acdh:
  stage: package
  extends:
    - .docker
    - .storybook
  variables:
    DOCKER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/storybook:release
    DOCKER_CURRENT_IMAGE: ${CI_REGISTRY_IMAGE}/storybook:$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG'
