include:
  - template: Auto-DevOps.gitlab-ci.yml

# All variables are passed into the Docker build context via `AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS`,
# which is set in the GitLab UI:
# `--build-arg NEXT_PUBLIC_BASE_URL --build-arg NEXT_PUBLIC_SSHOC_API_BASE_URL --build-arg GITLAB_ACCESS_TOKEN --build-arg NEXT_PUBLIC_GITLAB_PROJECT_ID --build-arg NEXT_PUBLIC_GITLAB_REPOSITORY_CURRENT_BRANCH --build-arg NEXT_PUBLIC_GITLAB_BASE_URL --build-arg NEXT_PUBLIC_GITLAB_REPOSITORY --build-arg NEXT_PUBLIC_GITLAB_REPOSITORY_BRANCH --build-arg NEXT_PUBLIC_GITLAB_APP_ID --build-arg NEXT_PUBLIC_MATOMO_BASE_URL --build-arg NEXT_PUBLIC_MATOMO_APP_ID --build-arg NEXT_PUBLIC_GOOGLE_SITE_ID`.
build:
  variables:
    GITLAB_ACCESS_TOKEN: $GITLAB_ACCESS_TOKEN
    NEXT_PUBLIC_GITLAB_PROJECT_ID: $NEXT_PUBLIC_GITLAB_PROJECT_ID
    NEXT_PUBLIC_GITLAB_BASE_URL: $NEXT_PUBLIC_GITLAB_BASE_URL
    NEXT_PUBLIC_GITLAB_REPOSITORY: $NEXT_PUBLIC_GITLAB_REPOSITORY
    NEXT_PUBLIC_GITLAB_REPOSITORY_BRANCH: $NEXT_PUBLIC_GITLAB_REPOSITORY_BRANCH
    NEXT_PUBLIC_GITLAB_APP_ID: $NEXT_PUBLIC_GITLAB_APP_ID
    NEXT_PUBLIC_MATOMO_BASE_URL: $NEXT_PUBLIC_MATOMO_BASE_URL
    NEXT_PUBLIC_GITLAB_REPOSITORY_CURRENT_BRANCH: $CI_COMMIT_REF_NAME
    REVALIDATION_TOKEN: $K8S_SECRET_REVALIDATION_TOKEN
    SMTP_SERVER: $K8S_SECRET_SMTP_SERVER
    SMTP_PORT: $K8S_SECRET_SMTP_PORT
    SSHOC_CONTACT_EMAIL_ADDRESS: $K8S_SECRET_SSHOC_CONTACT_EMAIL_ADDRESS
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop"
      variables:
        NEXT_PUBLIC_BASE_URL: 'https://sshoc-marketplace.acdh-dev.oeaw.ac.at'
        NEXT_PUBLIC_SSHOC_API_BASE_URL: 'https://sshoc-marketplace-api.acdh-dev.oeaw.ac.at'
        NEXT_PUBLIC_MATOMO_APP_ID: '190'
    - if: $CI_COMMIT_REF_NAME == "stage"
      variables:
        NEXT_PUBLIC_BASE_URL: 'https://sshoc-marketplace-stage.acdh-dev.oeaw.ac.at'
        NEXT_PUBLIC_SSHOC_API_BASE_URL: 'https://sshoc-marketplace-api-stage.acdh-dev.oeaw.ac.at'
        NEXT_PUBLIC_MATOMO_APP_ID: '198'
    - if: $CI_COMMIT_REF_NAME == "main"
      variables:
        NEXT_PUBLIC_BASE_URL: 'https://marketplace.sshopencloud.eu'
        NEXT_PUBLIC_SSHOC_API_BASE_URL: 'https://marketplace-api.sshopencloud.eu'
        NEXT_PUBLIC_MATOMO_APP_ID: '179'
        NEXT_PUBLIC_GOOGLE_SITE_ID: 'nGy-4NymUoG2gvqsocWhF8A7TY9wVh5bAVIrPMNeC8M'
        NEXT_PUBLIC_GITLAB_APP_ID: '21942eaff17c3fc7edddc9357bdad978bb0067fce4992be7dc42e07a5fd3be96'
    - when: on_success
