variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  # DOCKER_BUILDKIT: 1

stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
    - cluster
  variables:
    NEXT_PUBLIC_BASE_URL: $NEXT_PUBLIC_BASE_URL
    NEXT_PUBLIC_SSHOC_API_BASE_URL: $NEXT_PUBLIC_SSHOC_API_BASE_URL
    NEXT_PUBLIC_GITLAB_BASE_URL: $NEXT_PUBLIC_GITLAB_BASE_URL
    NEXT_PUBLIC_GITLAB_REPOSITORY: $NEXT_PUBLIC_GITLAB_REPOSITORY
    NEXT_PUBLIC_GITLAB_REPOSITORY_BRANCH: $NEXT_PUBLIC_GITLAB_REPOSITORY_BRANCH
    NEXT_PUBLIC_GITLAB_APP_ID: $NEXT_PUBLIC_GITLAB_APP_ID
    NEXT_PUBLIC_MATOMO_BASE_URL: $NEXT_PUBLIC_MATOMO_BASE_URL
    NEXT_PUBLIC_MATOMO_APP_ID: $NEXT_PUBLIC_MATOMO_APP_ID
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG || docker pull $CI_REGISTRY_IMAGE:main ||
      true
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      --cache-from=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --cache-from=$CI_REGISTRY_IMAGE:main
      --build-arg NEXT_PUBLIC_BASE_URL --build-arg NEXT_PUBLIC_SSHOC_API_BASE_URL --build-arg
      NEXT_PUBLIC_GITLAB_BASE_URL --build-arg NEXT_PUBLIC_GITLAB_REPOSITORY --build-arg
      NEXT_PUBLIC_GITLAB_REPOSITORY_BRANCH --build-arg NEXT_PUBLIC_GITLAB_APP_ID --build-arg
      NEXT_PUBLIC_MATOMO_BASE_URL --build-arg NEXT_PUBLIC_MATOMO_APP_ID .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - develop
    - stage
    - main
