# build
FROM node:10-alpine as build

WORKDIR /usr/src/app

COPY package.json yarn.lock ./
RUN yarn --silent

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY src ./src
COPY public ./public
COPY .storybook/ ./.storybook
RUN yarn build:storybook --quiet

# serve
FROM node:10-alpine

COPY --from=build /usr/src/app/storybook-static /usr/share/app

EXPOSE 9009

CMD ["npx", "serve", "-n", "-l", "9009", "/usr/share/app"]
