version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITLAB_BASE_URL
        - GITLAB_REPOSITORY
        - GITLAB_REPOSITORY_BRANCH
        - GITLAB_ACCESS_TOKEN
        - SSHOC_OPENAPI_DOCUMENT_URL
        - NEXT_PUBLIC_SSHOC_BASE_URL
        - NEXT_PUBLIC_SSHOC_API_BASE_URL
        - NEXT_PUBLIC_RECAPTCHA_SITE_KEY
        - NEXT_PUBLIC_MATOMO_BASE_URL
        - NEXT_PUBLIC_MATOMO_SITE_ID
    environment:
      - SSHOC_API_BASE_URL=http://marketplace:8080
    volumes:
      - image_cache:/usr/src/app/.next/cache/images
    ports:
      - 3000:3000
    networks:
      - sshoc-marketplace-backend_default

volumes:
  image_cache:

networks:
  sshoc-marketplace-backend_default:
    external: true
