ignoredBuiltDependencies:
  - unrs-resolver
onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks
patchedDependencies:
  '@stefanprobst/next-svg': patches/@stefanprobst__next-svg.patch
  final-form: patches/final-form.patch
  next: patches/next.patch
