name: Build and deploy Docker image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker (production)
        id: meta-production
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=main

      - name: Build and push Docker image (production)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta-production.outputs.tags }}
          labels: ${{ steps.meta-production.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=https://marketplace-api.sshopencloud.eu
            NEXT_PUBLIC_APP_BASE_URL=https://marketplace.sshopencloud.eu
            NEXT_PUBLIC_BOTS=enabled
            NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG=sshoc-marketplace-cms
            NEXT_PUBLIC_KEYSTATIC_GITHUB_REPO_NAME=sshoc-marketplace-frontend
            NEXT_PUBLIC_KEYSTATIC_GITHUB_REPO_OWNER=sshoc
            NEXT_PUBLIC_KEYSTATIC_MODE="github"
            NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=nGy-4NymUoG2gvqsocWhF8A7TY9wVh5bAVIrPMNeC8M
            NEXT_PUBLIC_MATOMO_BASE_URL=https://matomo.acdh.oeaw.ac.at/
            NEXT_PUBLIC_MATOMO_ID=179
            NEXT_PUBLIC_GITHUB_REPOSITORY=sshoc/sshoc-marketplace-frontend
            NEXT_PUBLIC_GITHUB_REPOSITORY_BRANCH=main
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
            "KEYSTATIC_GITHUB_CLIENT_ID=${{ secrets.KEYSTATIC_GITHUB_CLIENT_ID }}"
            "KEYSTATIC_GITHUB_CLIENT_SECRET=${{ secrets.KEYSTATIC_GITHUB_CLIENT_SECRET }}"
            "KEYSTATIC_SECRET=${{ secrets.KEYSTATIC_SECRET }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to cluster (production)
        uses: acdh-oeaw/deploy-action@v1
        with:
          token: ${{ secrets.RANCHER_API_TOKEN }}
          project: c-m-6hwgqq2g:p-jv25s
          deployment: sshoc-marketplace-frontend:sshoc-mp-frontend

      - name: Extract metadata (tags, labels) for Docker (stage)
        id: meta-stage
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=stage

      - name: Build and push Docker image (stage)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta-stage.outputs.tags }}
          labels: ${{ steps.meta-stage.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=https://sshoc-marketplace-api-stage.acdh-dev.oeaw.ac.at
            NEXT_PUBLIC_APP_BASE_URL=https://sshoc-marketplace-stage.acdh-dev.oeaw.ac.at
            NEXT_PUBLIC_BOTS=disabled
            NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG=sshoc-marketplace-cms
            NEXT_PUBLIC_KEYSTATIC_GITHUB_REPO_NAME=sshoc-marketplace-frontend
            NEXT_PUBLIC_KEYSTATIC_GITHUB_REPO_OWNER=sshoc
            NEXT_PUBLIC_KEYSTATIC_MODE="github"
            NEXT_PUBLIC_MATOMO_BASE_URL=https://matomo.acdh.oeaw.ac.at/
            NEXT_PUBLIC_MATOMO_ID=198
            NEXT_PUBLIC_GITHUB_REPOSITORY=sshoc/sshoc-marketplace-frontend
            NEXT_PUBLIC_GITHUB_REPOSITORY_BRANCH=main
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
            "KEYSTATIC_GITHUB_CLIENT_ID=${{ secrets.KEYSTATIC_GITHUB_CLIENT_ID }}"
            "KEYSTATIC_GITHUB_CLIENT_SECRET=${{ secrets.KEYSTATIC_GITHUB_CLIENT_SECRET }}"
            "KEYSTATIC_SECRET=${{ secrets.KEYSTATIC_SECRET }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to cluster (stage)
        uses: acdh-oeaw/deploy-action@v1
        with:
          token: ${{ secrets.RANCHER_API_TOKEN }}
          project: c-m-6hwgqq2g:p-jv25s
          deployment: sshoc-marketplace-frontend:sshoc-mp-frontendstg

      - name: Extract metadata (tags, labels) for Docker (dev)
        id: meta-dev
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=dev

      - name: Build and push Docker image (dev)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta-dev.outputs.tags }}
          labels: ${{ steps.meta-dev.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=https://sshoc-marketplace-api.acdh-dev.oeaw.ac.at
            NEXT_PUBLIC_APP_BASE_URL=https://sshoc-marketplace.acdh-dev.oeaw.ac.at
            NEXT_PUBLIC_BOTS=disabled
            NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG=sshoc-marketplace-cms
            NEXT_PUBLIC_KEYSTATIC_GITHUB_REPO_NAME=sshoc-marketplace-frontend
            NEXT_PUBLIC_KEYSTATIC_GITHUB_REPO_OWNER=sshoc
            NEXT_PUBLIC_KEYSTATIC_MODE="github"
            NEXT_PUBLIC_MATOMO_BASE_URL=https://matomo.acdh.oeaw.ac.at/
            NEXT_PUBLIC_MATOMO_ID=190
            NEXT_PUBLIC_GITHUB_REPOSITORY=sshoc/sshoc-marketplace-frontend
            NEXT_PUBLIC_GITHUB_REPOSITORY_BRANCH=main
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
            "KEYSTATIC_GITHUB_CLIENT_ID=${{ secrets.KEYSTATIC_GITHUB_CLIENT_ID }}"
            "KEYSTATIC_GITHUB_CLIENT_SECRET=${{ secrets.KEYSTATIC_GITHUB_CLIENT_SECRET }}"
            "KEYSTATIC_SECRET=${{ secrets.KEYSTATIC_SECRET }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to cluster (dev)
        uses: acdh-oeaw/deploy-action@v1
        with:
          token: ${{ secrets.RANCHER_API_TOKEN }}
          project: c-m-6hwgqq2g:p-jv25s
          deployment: sshoc-marketplace-frontend:sshoc-mp-frontenddev
